version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
    environment:
      - POSTGRES_DB=postgre
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
